In [1]:
!pip install -q ucimlrepo

In [2]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

#Loading the UCI PhiUSIIL Phishing URL (Website) dataset
dataset = fetch_ucirepo(id=967)
X = dataset.data.features
y = dataset.data.targets

print("Features shape:",X.shape)
print("Target shape:",y.shape)
display(X.head())
display(y.head())

Features shape: (235795, 54)
Target shape: (235795, 1)

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,1,0,0,1,34,20,28,119,0,124
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,0,0,0,1,50,9,8,39,0,217
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0,0,0,1,10,2,7,42,2,5
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,0,1,1,1,3,27,15,22,1,31
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,1,1,0,1,244,15,34,72,1,85

   label
0      1
1      1
2      1
3      1
4      1

In [3]:
print("Target column:")
print(y.columns)

print("\nClass counts:")
print(y.iloc[:, 0].value_counts())

Target column:
Index(['label'], dtype='object')

Class counts:
label
1    134850
0    100945
Name: count, dtype: int64

In [4]:
#Checking the dataset for missing values and duplicates

print("Missing values in X:")
print(X.isnull().sum().sum())

print("\nDuplicate rows in X:")
print(X.duplicated().sum())

print("\nData types:")
print(X.dtypes.value_counts())

Missing values in X:
0

Duplicate rows in X:
0

Data types:
int64      40
float64    10
object      4
Name: count, dtype: int64

In [5]:
#Finding the columns that contain text

text_columns = X.select_dtypes(include="object").columns

print("Text columns:")
print(list(text_columns))

Text columns:
['URL', 'Domain', 'TLD', 'Title']

In [6]:
#Removing text columns that we won't use for the first models

X_ml = X.drop(columns=["URL", "Domain", "TLD", "Title"])

print("Original features:",X.shape[1])
print("ML features:",X_ml.shape[1])
print("\nML-ready data shape:")
print(X_ml.shape)

Original features: 54
ML features: 50

ML-ready data shape:
(235795, 50)

In [7]:
#Preparing the target labels

y_ml = y["label"]

print("Target values:")
print(y_ml.value_counts())

print("\nFeature shape:",X_ml.shape)
print("Target shape:",y_ml.shape)

Target values:
label
1    134850
0    100945
Name: count, dtype: int64

Feature shape: (235795, 50)
Target shape: (235795,)

In [8]:
#Now splitting the data into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_ml,y_ml, test_size=0.20,random_state=42,stratify=y_ml)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)
print("\nTraining labels:")
print(y_train.value_counts())
print("\nTesting labels:")
print(y_test.value_counts())

Training data: (188636, 50)
Testing data: (47159, 50)

Training labels:
label
1    107880
0     80756
Name: count, dtype: int64

Testing labels:
label
1    26970
0    20189
Name: count, dtype: int64

In [9]:
#Now looking at all of the features we can use for the baseline

print("Available features:")
print(list(X_ml.columns))

Available features:
['URLLength', 'DomainLength', 'IsDomainIP', 'URLSimilarityIndex', 'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength', 'HasTitle', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef', 'NoOfExternalRef']

In [10]:
#Showing features by their column numbers

for i, column in enumerate(X_ml.columns):
    print(i, column)

0 URLLength
1 DomainLength
2 IsDomainIP
3 URLSimilarityIndex
4 CharContinuationRate
5 TLDLegitimateProb
6 URLCharProb
7 TLDLength
8 NoOfSubDomain
9 HasObfuscation
10 NoOfObfuscatedChar
11 ObfuscationRatio
12 NoOfLettersInURL
13 LetterRatioInURL
14 NoOfDegitsInURL
15 DegitRatioInURL
16 NoOfEqualsInURL
17 NoOfQMarkInURL
18 NoOfAmpersandInURL
19 NoOfOtherSpecialCharsInURL
20 SpacialCharRatioInURL
21 IsHTTPS
22 LineOfCode
23 LargestLineLength
24 HasTitle
25 DomainTitleMatchScore
26 URLTitleMatchScore
27 HasFavicon
28 Robots
29 IsResponsive
30 NoOfURLRedirect
31 NoOfSelfRedirect
32 HasDescription
33 NoOfPopup
34 NoOfiFrame
35 HasExternalFormSubmit
36 HasSocialNet
37 HasSubmitButton
38 HasHiddenFields
39 HasPasswordField
40 Bank
41 Pay
42 Crypto
43 HasCopyrightInfo
44 NoOfImage
45 NoOfCSS
46 NoOfJS
47 NoOfSelfRef
48 NoOfEmptyRef
49 NoOfExternalRef

In [11]:
#Checking on some features I may use for the rule based baseline

baseline_features = [
    "IsDomainIP",
    "HasObfuscation",
    "HasPasswordField",
    "HasExternalFormSubmit",
    "NoOfURLRedirect",
    "NoOfExternalRef"
]

for feature in baseline_features:
    print("\n", feature)
    print(X_ml[feature].value_counts().head(10))

 IsDomainIP
IsDomainIP
0    235157
1       638
Name: count, dtype: int64

 HasObfuscation
HasObfuscation
0    235310
1       485
Name: count, dtype: int64

 HasPasswordField
HasPasswordField
0    211682
1     24113
Name: count, dtype: int64

 HasExternalFormSubmit
HasExternalFormSubmit
0    225423
1     10372
Name: count, dtype: int64

 NoOfURLRedirect
NoOfURLRedirect
0    204331
1     31464
Name: count, dtype: int64

 NoOfExternalRef
NoOfExternalRef
0     55710
1     23885
3     11149
2      9241
4      4381
5      2572
8      2563
11     2553
7      2531
9      2506
Name: count, dtype: int64

In [12]:
#Creating a simple rule based phishing baseline

def rule_based_prediction(data):
    score = (
        (data["IsDomainIP"] == 1).astype(int)
        + (data["HasObfuscation"] == 1).astype(int)
        + (data["HasPasswordField"] == 1).astype(int)
        + (data["HasExternalFormSubmit"] == 1).astype(int)
        + (data["NoOfURLRedirect"] > 0).astype(int)
        + (data["NoOfExternalRef"] > 5).astype(int)
    )

    #1 = Acceptable legitimate, 0 = phishing

    predictions = (score < 2).astype(int)
    return predictions

#Test the baseline on the testing data
baseline_predictions = rule_based_prediction(X_test)

print("Baseline predictions:")
print(pd.Series(baseline_predictions).value_counts())

Baseline predictions:
1    39218
0     7941
Name: count, dtype: int64

In [13]:
#Evaluaing the rule based baseline

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

baseline_accuracy = accuracy_score(y_test, baseline_predictions)

#Use 0 as the positive class b/c 0 = phishing
baseline_precision = precision_score(y_test, baseline_predictions, pos_label=0)
baseline_recall = recall_score(y_test,baseline_predictions, pos_label=0)
baseline_f1 = f1_score(y_test, baseline_predictions,pos_label=0)

print("Rule-Based Baseline Results")
print("---------------------------")
print("Accuracy:",round(baseline_accuracy, 4))
print("Precision:", round(baseline_precision,4))
print("Recall:", round(baseline_recall,4))
print("F1-score:", round(baseline_f1, 4))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, baseline_predictions))

Rule-Based Baseline Results
---------------------------
Accuracy: 0.4295
Precision: 0.0773
Recall: 0.0304
F1-score: 0.0437

Confusion Matrix:
[[  614 19575]
 [ 7327 19643]]

In [14]:
#Training the first machine learning model

from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter=1000,random_state=42)

logistic_model.fit(X_train,y_train)
logistic_predictions = logistic_model.predict(X_test)

print("Logistic Regression model trained successfully.")
print("Number of predictions:",len(logistic_predictions))

Logistic Regression model trained successfully.
Number of predictions: 47159

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
#Scaling the data before training Logistic Regression *Again* (second test)

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_scaled, y_train)

logistic_predictions = logistic_model.predict(X_test_scaled)

print("Logistic Regression trained successfully after scaling.")
print("Number of predictions:", len(logistic_predictions))

Logistic Regression trained successfully after scaling.
Number of predictions: 47159

In [16]:
#Evaluating the Logistic Regression model

logistic_accuracy = accuracy_score(y_test, logistic_predictions)

logistic_precision = precision_score(y_test, logistic_predictions, pos_label=0)

logistic_recall = recall_score(y_test, logistic_predictions, pos_label=0)

logistic_f1 = f1_score(y_test, logistic_predictions, pos_label=0)

print("Logistic Regression Results")
print("---------------------------")
print("Accuracy:", round(logistic_accuracy, 4))
print("Precision:", round(logistic_precision, 4))
print("Recall:", round(logistic_recall, 4))
print("F1-score:", round(logistic_f1, 4))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, logistic_predictions))

Logistic Regression Results
---------------------------
Accuracy: 0.9999
Precision: 1.0
Recall: 0.9997
F1-score: 0.9999

Confusion Matrix:
[[20183     6]
 [    0 26970]]

In [17]:
#Training the Decision Tree model

from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state = 42)
decision_tree.fit(X_train,y_train)
decision_tree_predictions = decision_tree.predict(X_test)

print("Decision Tree model trained successfully.")
print("Number of test predictions:",len(decision_tree_predictions))

Decision Tree model trained successfully.
Number of test predictions: 47159

In [18]:
#Evaluating the Decision Tree model

decision_tree_accuracy = accuracy_score(y_test, decision_tree_predictions)
decision_tree_precision = precision_score(y_test,decision_tree_predictions,pos_label=0)
decision_tree_recall = recall_score(y_test,decision_tree_predictions,pos_label=0)
decision_tree_f1 = f1_score(y_test,decision_tree_predictions,pos_label=0)

print("Decision Tree Results")
print("--------------------")
print("Accuracy:", round(decision_tree_accuracy, 4))
print("Precision:", round(decision_tree_precision, 4))
print("Recall:", round(decision_tree_recall, 4))
print("F1-score:", round(decision_tree_f1, 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test,decision_tree_predictions))

Decision Tree Results
--------------------
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0

Confusion Matrix:
[[20189     0]
 [    0 26970]]

In [19]:
#Training the random Forest model

from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=100,random_state=42,n_jobs=-1)
random_forest.fit(X_train,y_train)
random_forest_predictions = random_forest.predict(X_test)

print("Random Forest model trained successfully.")
print("Number of test predictions:",len(random_forest_predictions))

Random Forest model trained successfully.
Number of test predictions: 47159

In [20]:
#Evaluating the random Forest model

random_forest_accuracy = accuracy_score(y_test,random_forest_predictions)
random_forest_precision = precision_score(y_test,random_forest_predictions,pos_label=0)
random_forest_recall = recall_score(y_test,random_forest_predictions,pos_label=0)
random_forest_f1 = f1_score(y_test,random_forest_predictions,pos_label=0)

print("Random Forest Results")
print("---------------------")
print("Accuracy:", round(random_forest_accuracy, 4))
print("Precision:", round(random_forest_precision, 4))
print("Recall:", round(random_forest_recall, 4))
print("F1-score:", round(random_forest_f1, 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test,random_forest_predictions))

Random Forest Results
---------------------
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0

Confusion Matrix:
[[20189     0]
 [    0 26970]]

In [21]:
#Checking which features are most important to the random Forest

feature_importance = pd.DataFrame({"Feature": X_train.columns,"Importance": random_forest.feature_importances_
                                   })

feature_importance = feature_importance.sort_values(by="Importance",ascending=False)

print("Top 15 Most Important Features:")
print(feature_importance.head(15).to_string(index=False))

Top 15 Most Important Features:
                   Feature  Importance
        URLSimilarityIndex    0.181075
           NoOfExternalRef    0.169265
                LineOfCode    0.146585
               NoOfSelfRef    0.108536
                 NoOfImage    0.084350
                    NoOfJS    0.072904
                   NoOfCSS    0.031598
              HasSocialNet    0.031526
          HasCopyrightInfo    0.025522
                   IsHTTPS    0.022940
         LargestLineLength    0.018937
NoOfOtherSpecialCharsInURL    0.018225
            HasDescription    0.018072
           NoOfDegitsInURL    0.012960
           DegitRatioInURL    0.008390

In [22]:
#Comparing important features between phishing & legit/credible websites

top_features = ["URLSimilarityIndex","NoOfExternalRef","LineOfCode","NoOfSelfRef","NoOfImage"]

for feature in top_features:
    print("\n" + feature)
    print("-" * len(feature))
    print(
        X_train.groupby(y_train)[feature]
        .agg(["mean", "median", "min", "max"])
    )

URLSimilarityIndex
------------------
             mean      median         min    max
label
0       49.588344   51.403306    0.155574  100.0
1      100.000000  100.000000  100.000000  100.0

NoOfExternalRef
---------------
            mean  median  min    max
label
0       1.121527     0.0    0    147
1      84.742918    45.0    0  19147

LineOfCode
----------
              mean  median  min     max
label
0        65.441367    12.0    2   29687
1      1945.564553  1106.0  102  442666

NoOfSelfRef
-----------
             mean  median  min    max
label
0        0.500124     0.0    0    120
1      112.856674    76.0    0  26596

NoOfImage
---------
            mean  median  min   max
label
0       0.861311     0.0    0   158
1      44.673498    25.0    0  8956

In [23]:
#Finding logistic regression's incorrect predictions

misclassified = X_test[
    y_test != logistic_predictions
].copy()

misclassified["Actual"] = y_test[y_test != logistic_predictions]
misclassified["Predicted"] = logistic_predictions[y_test != logistic_predictions]

print("Number of Logistic Regression errors:", len(misclassified))
print("\nMisclassified examples:")
print(misclassified.head(10).to_string())

Number of Logistic Regression errors: 6

Misclassified examples:
        URLLength  DomainLength  IsDomainIP  URLSimilarityIndex  CharContinuationRate  TLDLegitimateProb  URLCharProb  TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  ObfuscationRatio  NoOfLettersInURL  LetterRatioInURL  NoOfDegitsInURL  DegitRatioInURL  NoOfEqualsInURL  NoOfQMarkInURL  NoOfAmpersandInURL  NoOfOtherSpecialCharsInURL  SpacialCharRatioInURL  IsHTTPS  LineOfCode  LargestLineLength  HasTitle  DomainTitleMatchScore  URLTitleMatchScore  HasFavicon  Robots  IsResponsive  NoOfURLRedirect  NoOfSelfRedirect  HasDescription  NoOfPopup  NoOfiFrame  HasExternalFormSubmit  HasSocialNet  HasSubmitButton  HasHiddenFields  HasPasswordField  Bank  Pay  Crypto  HasCopyrightInfo  NoOfImage  NoOfCSS  NoOfJS  NoOfSelfRef  NoOfEmptyRef  NoOfExternalRef  Actual  Predicted
56879          25            18           0          100.000000              1.000000           0.522907     0.063592          3              1               0                   0               0.0                12             0.480                0            0.000                0               0                   0                           1                  0.040        1          33                112         1                  100.0               100.0           0       0             1                0                 0               0          0           0                      0             0                0                0                 0     0    0       0                 0          0        1       2            1             0                0       0          1
181237         44            35           0           65.946930              0.555556           0.000275     0.054219          3              4               0                   0               0.0                27             0.614                0            0.000                0               0                   0                           5                  0.114        1         520                780         1                    0.0                 0.0           0       0             1                0                 0               0          0           0                      0             0                1                1                 0     0    0       0                 1         10        2       0            0             0                0       0          1
7535           25            18           0          100.000000              1.000000           0.522907     0.068478          3              1               0                   0               0.0                12             0.480                0            0.000                0               0                   0                           1                  0.040        1          33                112         1                  100.0               100.0           0       0             1                0                 0               0          0           0                      0             0                0                0                 0     0    0       0                 0          0        1       2            1             0                0       0          1
159426         31            22           0          100.000000              1.000000           0.522907     0.067199          3              1               0                   0               0.0                17             0.548                0            0.000                0               0                   0                           2                  0.065        1          60                 98         1                  100.0               100.0           0       0             1                0                 0               0          0           0                      0             0                0                0                 0     0    0       0                 0          0        0       1            0             0                0       0          1
168451         29            20           0          100.000000              0.769231           0.010086     0.063366          2              2               0                   0               0.0                14             0.483                0            0.000                0               0                   0                           3                  0.103        1          17                665         1                    0.0                 0.0           0       0             1                1                 0               0          0           0                      0             0                0                0                 0     0    0       0                 0          0        1       3            0             0                0       0          1
112660         34            25           0           79.395085              0.666667           0.012178     0.053429          2              1               0                   0               0.0                17             0.500                3            0.088                0               0                   0                           2                  0.059        1         101                268         1                  100.0               100.0           1       0             1                0                 0               0          0           0                      0             0                1                1                 0     0    0       0                 1          4        1       0            0             0                2       0          1

In [24]:
#Example prediction from the held out test set

example_index = X_test.index[0]
example_features = X_test.loc[[example_index]]
example_prediction = random_forest.predict(example_features)[0]

print("Example Model Output")
print("--------------------")
print("Test case index:", example_index)
print("Actual label:", y_test.loc[example_index])

if example_prediction == 0:
    print("Predicted class: Phishing")
else:
    print("Predicted class: Legit")

Example Model Output
--------------------
Test case index: 173310
Actual label: 1
Predicted class: Legit

In [25]:
#Check the potential problematic features

suspicious_features = [
    "URLSimilarityIndex",
    "TLDLegitimateProb",
    "URLCharProb"
]

print("Current number of features:", X_ml.shape[1])
print("Suspicious features present:",
      [f for f in suspicious_features if f in X_ml.columns])

Current number of features: 50
Suspicious features present: ['URLSimilarityIndex', 'TLDLegitimateProb', 'URLCharProb']

In [26]:
#Removing the suspicious features for an additional experiment

X_no_suspicious = X_ml.drop(columns=suspicious_features)

print("Original features:",X_ml.shape[1])
print("Features after removal:",X_no_suspicious.shape[1])

Original features: 50
Features after removal: 47

In [27]:
#Creating a new train/test split without the suspicious features

X_train_ns, X_test_ns, y_train_ns, y_test_ns = train_test_split(
    X_no_suspicious,
    y_ml,
    test_size=0.20,
    random_state=42,
    stratify=y_ml
)

print("Training shape:", X_train_ns.shape)
print("Testing shape:", X_test_ns.shape)

Training shape: (188636, 47)
Testing shape: (47159, 47)

In [28]:
#Logistic regression without suspicious features

scaler_ns = StandardScaler()

X_train_ns_scaled =scaler_ns.fit_transform(X_train_ns)
X_test_ns_scaled =scaler_ns.transform(X_test_ns)

lr_ns = LogisticRegression(max_iter=2000, random_state=42)
lr_ns.fit(X_train_ns_scaled, y_train_ns)
lr_ns_pred = lr_ns.predict(X_test_ns_scaled)

print("Logistic Regression predictions:", len(lr_ns_pred))

Logistic Regression predictions: 47159

In [29]:
#Decision tree without suspicious features

dt_ns = DecisionTreeClassifier(random_state=42)
dt_ns.fit(X_train_ns, y_train_ns)

dt_ns_pred = dt_ns.predict(X_test_ns)

print("Decision Tree predictions:", len(dt_ns_pred))

Decision Tree predictions: 47159

In [30]:
#Random forest without suspicious features

rf_ns = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_ns.fit(X_train_ns, y_train_ns)
rf_ns_pred= rf_ns.predict(X_test_ns)

print("Random Forest predictions:", len(rf_ns_pred))

Random Forest predictions: 47159

In [31]:
#Evaluate models without suspicious features

def evaluate_model(name, y_true, y_pred):
    print(f"\n{name}")
    print("-" * 40)
    print("Accuracy :",accuracy_score(y_true, y_pred))
    print("Precision:",precision_score(y_true, y_pred, pos_label=0))
    print("Recall   :",recall_score(y_true, y_pred, pos_label=0))
    print("F1       :",f1_score(y_true, y_pred, pos_label=0))

evaluate_model("Logistic Regression - Without Suspicious Features", y_test_ns, lr_ns_pred)

evaluate_model("Decision Tree - Without Suspicious Features",y_test_ns,dt_ns_pred)

evaluate_model("Random Forest - Without Suspicious Features",y_test_ns,rf_ns_pred)

Logistic Regression - Without Suspicious Features
----------------------------------------
Accuracy : 0.999215420174304
Precision: 0.9994547437295529
Recall   : 0.9987121699935608
F1       : 0.9990833188811535

Decision Tree - Without Suspicious Features
----------------------------------------
Accuracy : 0.9990245764329184
Precision: 0.9986631677971975
Recall   : 0.999058893456833
F1       : 0.9988609914326747

Random Forest - Without Suspicious Features
----------------------------------------
Accuracy : 0.9998939756992302
Precision: 1.0
Recall   : 0.9997523403833771
F1       : 0.9998761548559681

In [32]:
#Display all 50 ML features
print("All ML features:")
for i, feature in enumerate(X_ml.columns, start=1):
    print(f"{i}. {feature}")

All ML features:
1. URLLength
2. DomainLength
3. IsDomainIP
4. URLSimilarityIndex
5. CharContinuationRate
6. TLDLegitimateProb
7. URLCharProb
8. TLDLength
9. NoOfSubDomain
10. HasObfuscation
11. NoOfObfuscatedChar
12. ObfuscationRatio
13. NoOfLettersInURL
14. LetterRatioInURL
15. NoOfDegitsInURL
16. DegitRatioInURL
17. NoOfEqualsInURL
18. NoOfQMarkInURL
19. NoOfAmpersandInURL
20. NoOfOtherSpecialCharsInURL
21. SpacialCharRatioInURL
22. IsHTTPS
23. LineOfCode
24. LargestLineLength
25. HasTitle
26. DomainTitleMatchScore
27. URLTitleMatchScore
28. HasFavicon
29. Robots
30. IsResponsive
31. NoOfURLRedirect
32. NoOfSelfRedirect
33. HasDescription
34. NoOfPopup
35. NoOfiFrame
36. HasExternalFormSubmit
37. HasSocialNet
38. HasSubmitButton
39. HasHiddenFields
40. HasPasswordField
41. Bank
42. Pay
43. Crypto
44. HasCopyrightInfo
45. NoOfImage
46. NoOfCSS
47. NoOfJS
48. NoOfSelfRef
49. NoOfEmptyRef
50. NoOfExternalRef

In [33]:
#Check which URL features are actually available in X_ml

url_features = [
    "URLLength",
    "DomainLength",
    "IsDomainIP",
    "URLSimilarityIndex",
    "CharContinuationRate",
    "TLDLegitimateProb",
    "URLCharProb",
    "TLDLength",
    "NoOfSubDomain",
    "HasObfuscation",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfDigitsInURL",
    "DigitRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "SpecialCharRatioInURL",
    "IsHTTPS"
]

available_url_features = [f for f in url_features if f in X_ml.columns]
missing_url_features = [f for f in url_features if f not in X_ml.columns]

print("Available URL features:", len(available_url_features))
print(available_url_features)
print("\nMissing URL features:", len(missing_url_features))
print(missing_url_features)

Available URL features: 19
['URLLength', 'DomainLength', 'IsDomainIP', 'URLSimilarityIndex', 'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'IsHTTPS']

Missing URL features: 3
['NoOfDigitsInURL', 'DigitRatioInURL', 'SpecialCharRatioInURL']

In [34]:
#Create the URL only feature dataset using available features

X_url = X_ml[available_url_features]

print("Number of URL-only features:", X_url.shape[1])
print("URL-only dataset shape:", X_url.shape)

Number of URL-only features: 19
URL-only dataset shape: (235795, 19)

In [35]:
#Features that can be calculated directly from a raw URL

app_features = [
    "URLLength",
    "DomainLength",
    "IsDomainIP",
    "CharContinuationRate",
    "TLDLength",
    "NoOfSubDomain",
    "HasObfuscation",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "IsHTTPS"
]

X_app = X_ml[app_features]

print("Number of app features:", X_app.shape[1])
print("App training dataset shape:", X_app.shape)
print("\nApp features:")
print(app_features)

Number of app features: 16
App training dataset shape: (235795, 16)

App features:
['URLLength', 'DomainLength', 'IsDomainIP', 'CharContinuationRate', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'IsHTTPS']

In [36]:
#Create train/test split for the app model

X_train_app, X_test_app, y_train_app, y_test_app = train_test_split(
    X_app,
    y_ml,
    test_size=0.20,
    random_state=42,
    stratify=y_ml
)

print("App training shape:", X_train_app.shape)
print("App testing shape:", X_test_app.shape)

App training shape: (188636, 16)
App testing shape: (47159, 16)

In [37]:
#Train the Random forest model for the web app

app_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

app_model.fit(X_train_app, y_train_app)
app_pred= app_model.predict(X_test_app)

print("App model predictions:",len(app_pred))

App model predictions: 47159

In [38]:
#Evaluate the app model

print("Web App Random Forest Model")
print("-" * 40)
print("Accuracy :",accuracy_score(y_test_app, app_pred))
print("Precision:",precision_score(y_test_app, app_pred, pos_label=0))
print("Recall   :",recall_score(y_test_app, app_pred, pos_label=0))
print("F1       :",f1_score(y_test_app, app_pred, pos_label=0))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_app, app_pred))

Web App Random Forest Model
----------------------------------------
Accuracy : 0.9967980661167539
Precision: 0.9983089624987566
Recall   : 0.9942047649710238
F1       : 0.9962526368035737

Confusion Matrix:
[[20072   117]
 [   34 26936]]

In [40]:
#Extract URL based features for a new URL
from urllib.parse import urlparse
import re
import ipaddress

def extract_app_features(url):
    #adding a scheme if the user leaves it out
    if not url.startswith(("http://", "https://")):
        url = "http://" + url

    parsed = urlparse(url)
    domain = parsed.netloc.split("@")[-1].split(":")[0]
    path_and_query = parsed.path + parsed.query

    #URL len
    url_length = len(url)

    #Domain len
    domain_length = len(domain)

    #Checking whether domain is an IP address
    try:
        ipaddress.ip_address(domain)
        is_domain_ip = 1
    except ValueError:
        is_domain_ip = 0

    #top level domain len
    domain_parts = domain.split(".")
    tld = domain_parts[-1] if len(domain_parts) > 1 else ""
    tld_length = len(tld)

    #num of subdomains
    no_of_subdomain = max(len(domain_parts) - 2, 0)

    # Obfuscation/complications
    obfuscated_matches= re.findall(r"%[0-9A-Fa-f]{2}", url)
    no_of_obfuscated_char= len(obfuscated_matches)
    has_obfuscation =1 if no_of_obfuscated_char > 0 or "@"in url else 0

    obfuscation_ratio = (
        no_of_obfuscated_char / url_length
        if url_length > 0 else 0
    )

    #letters
    no_of_letters = sum(c.isalpha() for c in url)

    letter_ratio = (
        no_of_letters / url_length
        if url_length> 0 else 0
    )

    #special characters
    no_of_equals = url.count("=")
    no_of_qmark = url.count("?")
    no_of_ampersand = url.count("&")

    no_of_other_special = sum(
        not c.isalnum() and c not in "=?&"
        for c in url
    )

    #HTTPS
    is_https = 1 if parsed.scheme == "https" else 0

    #character continuation rate
    runs= re.findall(r"(.)\1+", url)
    continuation_rate = (
        max([len(run) for run in runs], default=1) / url_length
        if url_length > 0 else 0
    )

    return {
        "URLLength": url_length,
        "DomainLength": domain_length,
        "IsDomainIP": is_domain_ip,
        "CharContinuationRate": continuation_rate,
        "TLDLength": tld_length,
        "NoOfSubDomain": no_of_subdomain,
        "HasObfuscation": has_obfuscation,
        "NoOfObfuscatedChar": no_of_obfuscated_char,
        "ObfuscationRatio": obfuscation_ratio,
        "NoOfLettersInURL": no_of_letters,
        "LetterRatioInURL": letter_ratio,
        "NoOfEqualsInURL": no_of_equals,
        "NoOfQMarkInURL": no_of_qmark,
        "NoOfAmpersandInURL": no_of_ampersand,
        "NoOfOtherSpecialCharsInURL": no_of_other_special,
        "IsHTTPS": is_https
    }

In [41]:
test_url = "https://www.google.com"

test_features =extract_app_features(test_url)

print("Test URL:", test_url)
print("\nExtracted Features:")

for feature, value in test_features.items():
    print(f"{feature}: {value}")

Test URL: https://www.google.com

Extracted Features:
URLLength: 22
DomainLength: 14
IsDomainIP: 0
CharContinuationRate: 0.045454545454545456
TLDLength: 3
NoOfSubDomain: 1
HasObfuscation: 0
NoOfObfuscatedChar: 0
ObfuscationRatio: 0.0
NoOfLettersInURL: 17
LetterRatioInURL: 0.7727272727272727
NoOfEqualsInURL: 0
NoOfQMarkInURL: 0
NoOfAmpersandInURL: 0
NoOfOtherSpecialCharsInURL: 5
IsHTTPS: 1

In [42]:
#Comparing my URL feature extractor with the original dataset
sample_index = X_ml.index[0]
sample_url = X.loc[sample_index, "URL"]

#Extracting features from the URL
extracted_features = extract_app_features(sample_url)

#Comparing dataset values vs. my extracted values
comparison = pd.DataFrame({
    "Dataset Value": X_ml.loc[sample_index, app_features],
    "Extracted Value": pd.Series(extracted_features)
})

comparison["Difference"] = (
    comparison["Extracted Value"] - comparison["Dataset Value"]
)

print("Sample URL:")
print(sample_url)

display(comparison)

Sample URL:
https://www.southbankmosaics.com

                            Dataset Value  Extracted Value  Difference
URLLength                          31.000         32.00000     1.00000
DomainLength                       24.000         24.00000     0.00000
IsDomainIP                          0.000          0.00000     0.00000
CharContinuationRate                1.000          0.03125    -0.96875
TLDLength                           3.000          3.00000     0.00000
NoOfSubDomain                       1.000          1.00000     0.00000
HasObfuscation                      0.000          0.00000     0.00000
NoOfObfuscatedChar                  0.000          0.00000     0.00000
ObfuscationRatio                    0.000          0.00000     0.00000
NoOfLettersInURL                   18.000         27.00000     9.00000
LetterRatioInURL                    0.581          0.84375     0.26275
NoOfEqualsInURL                     0.000          0.00000     0.00000
NoOfQMarkInURL                      0.000          0.00000     0.00000
NoOfAmpersandInURL                  0.000          0.00000     0.00000
NoOfOtherSpecialCharsInURL          1.000          5.00000     4.00000
IsHTTPS                             1.000          1.00000     0.00000

In [43]:
#Final URL only feature set for the web app

app_features_final = [
    "DomainLength",
    "IsDomainIP",
    "TLDLength",
    "NoOfSubDomain",
    "HasObfuscation",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "IsHTTPS"
]

#Create the final app dataset
X_app_final = X_ml[app_features_final]

print("Final app features:", len(app_features_final))
print(app_features_final)
print("Shape:", X_app_final.shape)

Final app features: 11
['DomainLength', 'IsDomainIP', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'IsHTTPS']
Shape: (235795, 11)

In [45]:
import joblib

#saving final web app model
joblib.dump(final_app_model, "phishing_app_model.pkl")

# the exact feature list
joblib.dump(app_features_final, "app_features.pkl")

print("Model saved successfully!")
print("Feature list saved successfully!")

Model saved successfully!
Feature list saved successfully!

In [46]:
!pip install -q streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 44.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 67.3 MB/s eta 0:00:00

In [47]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib
import re
import ipaddress
from urllib.parse import urlparse


#load model
model = joblib.load("phishing_app_model.pkl")
app_features = joblib.load("app_features.pkl")


#get features from the url
def extract_app_features(url):

    if not url.startswith(("http://", "https://")):
        url = "http://" + url

    parsed = urlparse(url)

    domain = parsed.netloc.split("@")[-1].split(":")[0]

    #domain length
    domain_length = len(domain)

    #check if domain is an ip
    try:
        ipaddress.ip_address(domain)
        is_domain_ip = 1
    except ValueError:
        is_domain_ip = 0

    #get tld info
    domain_parts = domain.split(".")

    tld = domain_parts[-1] if len(domain_parts) > 1 else ""

    tld_length = len(tld)

    #count subdomains
    no_of_subdomain = max(len(domain_parts) - 2, 0)

    #check for obfuscation/complication
    obfuscated_matches = re.findall(
        r"%[0-9A-Fa-f]{2}",
        url
    )

    no_of_obfuscated_char = len(obfuscated_matches)
    has_obfuscation = (
        1
        if no_of_obfuscated_char > 0 or "@" in url
        else 0
    )
    obfuscation_ratio = (
        no_of_obfuscated_char / len(url)
        if len(url) > 0
        else 0
    )

    #count url characters
    no_of_equals = url.count("=")
    no_of_qmark = url.count("?")
    no_of_ampersand = url.count("&")

    #check if https
    is_https = (
        1
        if parsed.scheme == "https"
        else 0
    )
    return {
        "DomainLength": domain_length,
        "IsDomainIP": is_domain_ip,
        "TLDLength": tld_length,
        "NoOfSubDomain": no_of_subdomain,
        "HasObfuscation": has_obfuscation,
        "NoOfObfuscatedChar": no_of_obfuscated_char,
        "ObfuscationRatio": obfuscation_ratio,
        "NoOfEqualsInURL": no_of_equals,
        "NoOfQMarkInURL": no_of_qmark,
        "NoOfAmpersandInURL": no_of_ampersand,
        "IsHTTPS": is_https
    }

#page setup
st.set_page_config(
    page_title="Phishing Website Detector",
    layout="centered"
)

#page title
st.title(" Phishing Website Detector")
st.write(
    "Enter a website URL below to analyze its "
    "phishing risk using a machine learning model."
)

st.info(
    "This application uses a Random Forest classifier "
    "trained on URL-based features from the PhiUSIIL "
    "phishing URL dataset."
)

#url input
url = st.text_input(
    "Enter Website URL",
    placeholder="https://example.com"
)

#analyze url
if st.button("Analyze Website", type="primary"):

    if not url.strip():
        st.warning("Please enter a website URL.")

    else:
        try:

            #get features / put into dataframe
            features = extract_app_features(url)
            input_data = pd.DataFrame(
                [features]
            )

            #keep features in the same order & make predics
            input_data = input_data[
                app_features
            ]
            prediction = model.predict(
                input_data
            )[0]

            #get prediction probabilities
            probabilities = model.predict_proba(
                input_data
            )[0]

            #get phishing probability
            phishing_index = list(
                model.classes_
            ).index(0)
            phishing_probability = (
                probabilities[phishing_index]
            )

            #show result
            st.subheader("Analysis Result")
            if prediction == 0:

                st.error(
                    "⚠️ PHISHING WEBSITE DETECTED"
                )

            else:

                st.success(
                    "WEBSITE CLASSIFIED AS LEGITIMATE"
                )

            #show probability
            st.metric(
                "Model-Estimated Phishing Probability",
                f"{phishing_probability * 100:.2f}%"
            )

            #set risk level
            if phishing_probability >= 0.70:
                st.error("Risk Level: HIGH")

            elif phishing_probability >= 0.40:

                st.warning("Risk Level: MEDIUM")

            else:
                st.success("Risk Level: LOW")

            #show features
            with st.expander(
                "View URL Features Analyzed"
            ):

                feature_display = pd.DataFrame({
                    "Feature": input_data.columns,
                    "Value": input_data.iloc[0].values
                })
                st.dataframe(
                    feature_display,
                    use_container_width=True,
                    hide_index=True
                )

            #disclaimers
            st.caption(
                "This application is a research prototype. "
                "Its prediction should not be treated as a "
                "guarantee that a website is safe or malicious."
            )

        except Exception as e:

            st.error(
                f"Unable to analyze this URL: {e}"
            )

Writing app.py

In [48]:
import os

print("app.py:", os.path.exists("app.py"))
print("model:", os.path.exists("phishing_app_model.pkl"))
print("features:", os.path.exists("app_features.pkl"))

app.py: True
model: True
features: True

In [49]:
!streamlit run app.py &>/content/streamlit.log &

In [50]:
from google.colab import output

app_url = output.eval_js("google.colab.kernel.proxyPort(8501)")
print(app_url)

https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev

In [51]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-07 20:31:38.053 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://8.228.30.107:8501

2026-10-07 20:32:48.100 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:32:48.695 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:32:50.006 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:32:51.517 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:32:55.549 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:32:59.196 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:01.725 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:05.004 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:09.237 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:12.090 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:16.029 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:18.932 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:22.437 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:25.602 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:28.587 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:34.742 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:41.280 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:45.020 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:49.541 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:54.716 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:33:59.100 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:06.485 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:14.034 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:19.743 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:24.164 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:31.494 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:38.946 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:45.195 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:52.308 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:34:57.322 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:03.182 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:10.682 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:15.911 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:29.053 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:36.183 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:44.497 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:50.892 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:35:58.770 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:04.128 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:12.092 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:17.696 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:23.107 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:34.501 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:39.251 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:45.196 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:48.601 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:51.100 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:54.668 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:36:57.425 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:00.919 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:04.219 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:07.952 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:12.198 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:14.698 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:18.925 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:21.922 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:26.237 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:29.701 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:33.015 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:38.029 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:42.734 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:49.916 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:55.152 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:37:59.113 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:03.355 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:16.364 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:25.070 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:33.273 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:44.827 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:48.492 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:53.483 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:38:57.923 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:39:02.513 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:39:07.677 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:39:12.506 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007
2026-10-07 20:39:16.492 Rejecting WebSocket connection with disallowed Origin or Host header: origin=https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev, host=m-s-kkb-usw4b2-2xhnl5wlp63md.us-west4-b.c.codatalab-user-runtimes.internal:8007

In [52]:
!pkill -f "streamlit run" || true

^C

In [53]:
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false &>/content/streamlit.log &

In [54]:
from google.colab import output

app_url = output.eval_js("google.colab.kernel.proxyPort(8501)")
print(app_url)

https://8501-m-s-kkb-usw4b2-2xhnl5wlp63md-b.us-west4-2.prod.colab.dev

In [55]:
#download the model files
from google.colab import files

files.download("phishing_app_model.pkl")
files.download("app_features.pkl")

In [56]:
from google.colab import files

files.download("app.py")